### ISSUE TITLE
not working with macos big sur. apple m1 chip

### ISSUE THREAD

**Issue by muokid3** [phalcon/homebrew-tap#25]
I get the following error

```
Error: phalcon@4.1.0: SHA256 mismatch
Expected: f85be1d1434368abd16e06b81e394487f81b5e2706220f01c85558ba486ee3e7
  Actual: 648aac07414f8c6e5c80728cf91fa8174bbd18dd41ae1a90168b510a507cf805
    File: /Users/muoki/Library/Caches/Homebrew/downloads/884d93653a90ca2920a90a10401cecfa589c3687aaf4c6fef8a58161027ee19a--php-psr-0.7.0.tar.gz
To retry an incomplete download, remove the file above.
```

I have removed the mentioned file and tried to reinstall again but i still get the same error. I am runnig php 7.4.26

**Comment by Ultimater** [comment]
Someone else appears to also be running into this:  
https://stackoverflow.com/questions/71390226/i-cant-install-phalcon-php-in-macbook-air-m1-with-monterey-why

The Expected you're getting is the sha256 of php-psr-1.0.0.tar.gz:
f85be1d1434368abd16e06b81e394487f81b5e2706220f01c85558ba486ee3e7 
The Actual you're getting is the sha256 of php-psr-0.7.0.tar.gz:
648aac07414f8c6e5c80728cf91fa8174bbd18dd41ae1a90168b510a507cf805

The README states that Phalcon 4.1.0 requires php-psr 1.0.0. So you'd need to grab that exact version of PSR in order to pass the hash: https://github.com/jbboehr/php-psr

Alternatively, you can also just use a slightly older Phalcon 4 which uses the installed version of psr you're using:
`brew install phalcon@4.0.4`
